name: budget_planner
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.9.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: 
  fl_chart: ^0.64.0
  intl: ^0.20.2
  go_router: ^13.0.1 
  shared_preferences: ^2.5.3
  provider: ^6.1.5+1
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  # sign_in_with_apple: ^7.0.1
  google_sign_in: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.4.0
  lottie: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:

  uses-material-design: true
  assets: 
    - assets/images/tip_budget.png
    - assets/images/track_budget.png
    - assets/images/control_finance.png
    - assets/images/automate.png
    - assets/images/emergency.png
    - assets/images/cut.png
    - assets/images/50rule.png
    - assets/images/payoff.png
    - assets/images/purpose.png
    - assets/images/monthly.png
    - assets/images/app_icon1.png
    - assets/images/app_icon_raw.png
    - assets/animations/empty_box.json

    
    

